version: "2.1"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:3000"
    networks:
      - internal
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    networks:
      - internal
    restart: unless-stopped

networks:
  internal: {}
